version: "2"
services:
  redis:
    image: redis
    ports: 
      - "6379"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mat_frontend
    ports:
      - "3000:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mat_backend
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_PLACE_API_KEY=AIzaSyDU37WuK50EI7VUmdC7aSoie_pboKq7lSU

